### PR TITLE
Adding a page to allow running arbitrary robot commands

### PR DESCRIPTION
**Pull request by fschwach**
I have added a page "/checkCalibration" that I find useful in the calibration process. It allows building commands for the command queue, e.g. to check that tips are correctly picked up across the tip rack after calibration to the A1 tip. It is also useful for trying/developing new protocols. Commands are run immediately.
This is functional but not fully finished yet. It still needs some javascript to adjust the selectable parameters according to the labware. For that reason, I haven't yet added links to this page on any other page, so it is there for those who know about it but not so visible to the normal end user. We might need to go a step further and protect this page with a simple admin login (harcoded password should be enough) because it would be possible to use this feature to interfere with a running protocol and dispense liquids in arbitrary places, which could be a hazard.

### CODE REVIEW

**Comment by fschwach** [comment]
I re-visited the problem of pipette crashing into tips on the tip rack, which gets worse with distance from A1 position. Tried different spacing in equipment definition for the p1000 tip rack and setting the spacing to the new value of 9.1mm works very well. Now pickup of tips is smooth across the whole tip rack.

**Comment by theosanderson** [comment]
Awesome on the arbitrary commands - something I'd also considered and not got round to. Love the AJAX. Now that I'm here I've got into the habit of code review, so I'll point out the "chech" vs "check" typo.

Re. spacing: A) great discovery - I don't remember this so I imagine it might be a recent phenomenon. Maybe the robot itself has got out of calibration: https://support.opentrons.com/ot-one/hardware-maintenance/x-y-belt-calibration

I am reluctant to commit that change because it relies on other robots being out of calibration to the same extent. I think the "right way" to address this would be to recalibrate as above. I appreciate this may be more work than this monkey-patch, so if you prefer to have the patch in your repo, all good.

Definitely up for committing the arbitrary commands whenever you like. For my part I'm all in favour of empowering users by not putting a password on it - though a big warning sign might be in order.

Great stuff.

**Comment by fschwach** [comment]
I have reverted the spacing. As per commit message, we have checked the new spacing with a second robot and it doesn't work on that one, so I think you are right that the belt needs re-calibration. There is only the new checkCalibration page to pull now. Hope this is ok. Thanks!

**Comment by theosanderson** [comment]
Thanks - fantastic!

**Pull request merged**
